-- docs/migrations/006_admin_automation.sql
--
-- Aplicado em 12/06/2026 via Supabase MCP. Idempotente.
--
-- Suporte à automação da área ADMIN do dashboard (utils/admin_automation.py):
-- todas as rotinas que antes exigiam cliques humanos (Data Cleanup, Normalize
-- SKUs, fila REVISAR do de-para) passam a rodar sozinhas após cada coleta,
-- via cron (scripts/admin_auto.py) e por auto-run na página "🤖 Automação".
--
--   1. Tabela `admin_automation_runs` — auditoria de cada execução do motor
--      (trigger, etapas, contagens, watermark incremental). O dashboard lê
--      daqui o histórico; o motor degrada para logs/admin_automation.jsonl
--      se a tabela não existir.
--   2. Função `fn_marca_norm_seed` — normaliza marca crua → marca_norm UPPER
--      (mesmo CASE da migration 002, agora reutilizável).
--   3. RPC `seed_depara_nomes_novos` — insere no de-para os nomes coletados
--      que ainda não têm entrada (estado REVISAR, origem 'auto_seed').
--      Fecha o gap que antes dependia de classificação manual via CSV
--      (scripts/descobrir_nomes_novos.py).

-- ============================================================================
-- PASSO 1 — Tabela de auditoria das execuções da automação
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.admin_automation_runs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        uuid        NOT NULL DEFAULT gen_random_uuid(),
    trigger       text        NOT NULL DEFAULT 'manual',   -- pos_coleta | cron | dashboard_auto | dashboard_manual | manual
    status        text        NOT NULL DEFAULT 'running',  -- running | ok | partial | error | skipped
    dry_run       boolean     NOT NULL DEFAULT false,
    started_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz,
    duration_s    numeric,
    errors        integer     NOT NULL DEFAULT 0,
    watermark_id  bigint,                                  -- maior coletas.id varrido (scan incremental)
    steps         jsonb,                                   -- [{name, ok, duration_s, summary, details, error}]
    totals        jsonb                                    -- agregados (linhas deletadas/renomeadas/resolvidas…)
);

-- Alinha com as demais tabelas do projeto (acesso via service_role key)
ALTER TABLE public.admin_automation_runs DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_admin_automation_runs_started
    ON public.admin_automation_runs (started_at DESC);

-- ============================================================================
-- PASSO 2 — Marca crua → marca_norm canônica (CASE da migration 002)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.fn_marca_norm_seed(p_marca text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE LOWER(COALESCE(p_marca, ''))
        WHEN 'springer midea' THEN 'MIDEA' WHEN 'midea carrier' THEN 'MIDEA'
        WHEN 'springer' THEN 'MIDEA'       WHEN 'midea' THEN 'MIDEA'
        WHEN 'lg' THEN 'LG'                WHEN 'samsung' THEN 'SAMSUNG'
        WHEN 'electrolux' THEN 'ELECTROLUX' WHEN 'elgin' THEN 'ELGIN'
        WHEN 'philco' THEN 'PHILCO'        WHEN 'gree' THEN 'GREE'
        WHEN 'tcl' THEN 'TCL'              WHEN 'agratto' THEN 'AGRATTO'
        WHEN 'hisense' THEN 'HISENSE'      WHEN 'carrier' THEN 'CARRIER'
        WHEN 'consul' THEN 'CONSUL'        WHEN 'daikin' THEN 'DAIKIN'
        WHEN 'fujitsu' THEN 'FUJITSU'      WHEN 'hitachi' THEN 'HITACHI'
        WHEN 'haier' THEN 'HAIER'          WHEN 'york' THEN 'YORK'
        WHEN 'eos' THEN 'EOS'              WHEN 'hq' THEN 'HQ'
        WHEN 'aiwa' THEN 'AIWA'            WHEN 'vix' THEN 'VIX'
        WHEN 'rheem' THEN 'RHEEM'          WHEN 'kian' THEN 'KIAN'
        WHEN 'britânia' THEN 'BRITANIA'    WHEN 'britania' THEN 'BRITANIA'
        WHEN 'equation' THEN 'EQUATION'    WHEN 'delonghi' THEN 'DELONGHI'
        WHEN 'aufit' THEN 'AUFIT'          WHEN 'komeco' THEN 'KOMECO'
        ELSE NULL
    END;
$$;

-- ============================================================================
-- PASSO 3 — Seed automático de nomes novos no de-para (REVISAR)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.seed_depara_nomes_novos()
RETURNS jsonb LANGUAGE plpgsql SET search_path TO 'public' AS $$
DECLARE
    v_coletas int;
    v_rac     int;
BEGIN
    INSERT INTO produtos_depara_nome (nome_coletado, estado, marca_norm, origem)
    SELECT DISTINCT c.produto, 'REVISAR', fn_marca_norm_seed(c.marca), 'auto_seed'
    FROM coletas c
    WHERE c.produto IS NOT NULL
      AND c.estado_match IS NULL
    ON CONFLICT (nome_coletado) DO NOTHING;
    GET DIAGNOSTICS v_coletas = ROW_COUNT;

    INSERT INTO produtos_depara_nome (nome_coletado, estado, marca_norm, origem)
    SELECT DISTINCT r.produto_sku, 'REVISAR', fn_marca_norm_seed(r.marca_monitorada), 'auto_seed'
    FROM rac_monitoramento r
    WHERE r.produto_sku IS NOT NULL
      AND r.estado_match IS NULL
    ON CONFLICT (nome_coletado) DO NOTHING;
    GET DIAGNOSTICS v_rac = ROW_COUNT;

    RETURN jsonb_build_object(
        'ok', true,
        'novos_coletas', v_coletas,
        'novos_rac', v_rac
    );
END $$;
